### ISSUE TITLE
Improve 'opening directories' (multi-platform) wording in docs' introduction

### ISSUE THREAD

**Issue by dcarral** [atom/docs#112]
@ docs: To open a directory, choose "File >> Open"

Actually, "File >> Open Folder..." does the trick nowadays (v1.0.7)

**Comment by lee-dohm** [comment]
I think this is platform-dependent. On OS X, using `File >> Open` allows one to either open a directory or a file and there is no `File >> Open Folder...` menu item.

**Comment by dcarral** [comment]
Hmmm, exactly. https://github.com/atom/atom/tree/29a1fbc45f4bf2be059fb827204994e06c1437f3/menus

Good catch, I even didn't think about it! Thanks @lee-dohm ;)

**Comment by lee-dohm** [comment]
You're welcome :sunglasses:

**Comment by dcarral** [comment]
Knowing this, how could we solve this issue in a elegant manner? 

Without further reading/testing I don't know if:

- This fact (the platform-specific functionality and its possible misalignment with the docs content) is mentioned somewhere in the document.
- Wording for "menu items" is at least consistent across the book.

**Comment by lee-dohm** [comment]
The majority of the documentation has been written from the OS X perspective. There is a discussion around strategies for handling multiple platforms (#16) but no real progress has been made on that front. The way I've been writing these things in most communications is as an additional note like this:

> To open a directory, choose the menu item ''File >> Open'' on OS X or ''File >> Open Folder'' on other platforms and select a directory from the dialog.

**Comment by dcarral** [comment]
Thank you very much for the info. As you might have noticed I wasn't aware of current discussions/roadmap at all, sorry for that.

After checking the tasks mentioned in https://github.com/atom/atom/issues/7995, it looks like, at the moment, there's not planned work for #16 yet, right?

**Comment by lee-dohm** [comment]
> As you might have noticed I wasn't aware of current discussions/roadmap at all, sorry for that.

There's no need to apologize, we don't expect everyone to keep up with every minute detail of the project :laughing:

> it looks like, at the moment, there's not planned work for #16 yet, right?

To my knowledge, not at the moment, no.
