### ISSUE TITLE
Add documentation on file type -> language mapping

### ISSUE THREAD

**Issue by izuzak** [atom/docs#124]
See https://github.com/atom/atom/issues/1718#issuecomment-140751676 for context

**Comment by n8v** [comment]
Hey thanks, this is a great feature! And would be easier to use with documentation!

I guessed correctly but I'd like the docs to tell me how to determine the correct name for the scope to use and remind me not to use the period in the file extension(s).
```
  core:
    customFileTypes:
      "source.json" : [
        "template"
      ]          
```
