### ISSUE TITLE
Latest version's searching docs shows no results

### ISSUE THREAD

**Issue by ystkme** [atom/docs#130]
The version of search box of Atom's online documentation page, [atom.io/docs/](https://atom.io/docs), is latest by default. Now it's v1.1.0-beta.0. And I can't find any results for any searching keywords when I search by the latest version.

Of course you can change its version to the previous one and get proper results. But it's frustrating to change the version every time you search online, and it's not user-friendly (beginners can get confused).

I think searching docs should show proper results by its default version.

<a href="https://gyazo.com/ad7d1bb8f6b14d74d52e1ca8b8f8dec6"><img src="https://i.gyazo.com/ad7d1bb8f6b14d74d52e1ca8b8f8dec6.png" width="400"/></a>
<a href="https://gyazo.com/72522d0d011b49f808ba15e25cff110c"><img src="https://i.gyazo.com/72522d0d011b49f808ba15e25cff110c.png" width="400" /></a>

**Comment by thedaniel** [comment]
Thanks for this, I'll look into it.

**Comment by thedaniel** [comment]
Atom.io no longer attempts to import docs for prerelease versions.
