### ISSUE TITLE
Getting Started Side Menu on Website is incorrect

### ISSUE THREAD

**Issue by TheAlphaNerd** [atom/docs#137]
After clicking getting started the side panel only has links about upgrading to 1.0

This is very confusing as a new user

**Comment by 50Wliu** [comment]
This looks like a duplicate of #121 - please subscribe there for updates (and also, the docs that you're looking for :smile:).

**Comment by izuzak** [comment]
cc @thedaniel seems like more and more users are hitting this problem. Just a friendly ping in case that helps us prioritize tasks. :v:
