### ISSUE TITLE
Broken links in FAQ, info on contributing to Atom difficult to find.

### ISSUE THREAD

**Issue by sumyungguy** [atom/docs#146]
I'm a new user having trouble with some broken community packages. I was looking for general information on how packages are published to atom.io, who is responsible for them, and how I could perhaps contribute to fixing them, particularly when the original author is no longer active or responding to pull requests and so on. Eventually I tracked down the info, but I found it difficult to locate.

In the FAQ at https://atom.io/faq the two links under "How can I contribute to Atom?" are broken:

1 - "creating a package" - https://atom.io/docs/latest/creating-a-package
The content formerly at this URL has been mostly merged into "package: word count":
https://atom.io/docs/latest/hacking-atom-package-word-count
...and that seems to be the most appropriate place for the FAQ link to go to.

The "package: word count" title is somewhat unintuitive compared to the former "creating a package", and despite spending some time looking through the site, I only found the info about publishing by putting the broken link from the FAQ into the Wayback Machine at archive.org. There's not much to indicate that this single page contains the majority of the reference info about writing, debugging, and publishing packages.

I see in the planning outline that there's a whole chapter on contributing being considered, but in the meantime a little cleanup might be helpful. I'd like to suggest having a more descriptive name for the "package: word count" page, a better explanation of the contents in the opening paragraph, and maybe either a mini table of contents at the top of the page, or breaking out some of the sections separately so they can appear in the main table of contents, eg. creating, testing and debugging, and publishing. You might also consider renaming section 3.7 from "debugging" to "troubleshooting", since actual debugging is covered in the packages page.

The info about publishing could perhaps be moved or at least linked to the "Maintaining Your Packages" section in chapter 4, which is the first place I looked, but only found info on unpublishing...

2 - "contributing guide" - https://atom.io/docs/latest/contributing
This content is in the atom master at https://github.com/atom/atom/blob/master/CONTRIBUTING.md and contains all kinds of very useful information... but I couldn't find it anywhere in the docs site, and again only located it by putting the broken FAQ link into the Wayback Machine.

**Comment by lee-dohm** [comment]
This issue was moved to atom/atom.io#44

**Comment by lee-dohm** [comment]
I moved this to the https://github.com/atom/atom.io repository, since that's where we track bugs with the non-docs portion of the https://atom.io website. Please subscribe to the new issue there: https://github.com/atom/atom.io/issues/44
