### ISSUE TITLE
Chapter 2.2 and 2.3 may be out of date.

### ISSUE THREAD

**Issue by letientai299** [atom/docs#148]
Hi, I'm a Atom beginner. So that I've start to read the Atom Flight Manual and found those following shortcut are not work like described in the docs:
In section 2.3
```
ctrl-shift-P
    Select up
ctrl-shift-N
    Select down
ctrl-shift-B
    Select previous character
ctrl-shift-F
    Select next character
```
And in section 2.2
```
cmd-right, ctrl-E
    Move to end of line
cmd-left, ctrl-A
    Move to first character of line
```
I'm using Atom 1.3.1 in window 10. Not sure if those above 'ctrl' and 'cmd' are interchangable, as I don't have a Mac to try them.

**Comment by lee-dohm** [comment]
The keybindings mentioned are OS X specific at this point. Please see https://github.com/atom/docs/issues/16 for plans on how we want to fix that.
