### ISSUE TITLE
https://atom.io/docs links to old FAQ topics under "Pinned Discussions"

### ISSUE THREAD

**Issue by WalterGR** [atom/docs#151]
(I don't know if this is intentional or not.)

"Pinned Discussions" on https://atom.io/docs links to two older topics which were both unpinned February 28 2015:

*  [FAQ: Best Practices](https://discuss.atom.io/t/faq-best-practices/11340)
*  [Have a question for the Atom team? Check here first!](https://discuss.atom.io/t/have-a-question-for-the-atom-team-check-here-first/7979)

It seems like the new FAQ category - https://discuss.atom.io/c/faq - has superseded them.

The "FAQ: Best Practices" topic is even older than the "[Archived FAQs (see FAQ category for all current FAQs)](https://discuss.atom.io/t/archived-faqs-see-faq-category-for-all-current-faqs/14981)" topic.

**Comment by lee-dohm** [comment]
This was fixed recently. Thanks for reporting!
