### ISSUE TITLE
Broken Space Pen linkl

### ISSUE THREAD

**Issue by redbassett** [atom/docs#165]
On the [Iconography page](https://atom.io/docs/latest/hacking-atom-iconography) of the Atom Flight Manual (section 3.6 in the latest (1.4.3) revision), there is a now-dead link to Space Pen.

**Comment by 50Wliu** [comment]
The new link is now http://atom-archive.github.io/space-pen/.

**Comment by redbassett** [comment]
Thanks @stevemao and @50Wliu!
