### ISSUE TITLE
Search box should be at the top of every page

### ISSUE THREAD

**Issue by lee-dohm** [atom/docs#17]
If I use the ePub, Kindle or PDF versions, I can search the documentation in their respective viewers. From the main documentation page, there is a search box that will allow me to search the Atom Flight Manual. But in the API documentation, there is a search box at the top of *every* page:

![screen shot 2015-03-12 at 5 13 37 pm](https://cloud.githubusercontent.com/assets/1038121/6630883/28c9728e-c8db-11e4-8622-1bc39501869d.png)

The same is not true for the Flight Manual:

![screen shot 2015-03-12 at 5 14 27 pm](https://cloud.githubusercontent.com/assets/1038121/6630888/44d14e84-c8db-11e4-81ea-a0ba17bda0c4.png)

**Comment by schacon** [comment]
Ah, that's a good idea. I'll put this on the TODO list.

**Comment by izuzak** [comment]
There should now be a searchbox on individual pages in the flight manual.
