### ISSUE TITLE
Atom.io integration

### ISSUE THREAD

**Issue by schacon** [atom/docs#4]
We should take the HTML output of the book and present it on Atom.io in place of the current [Guides content](https://atom.io/docs/latest/).

This includes being able to version the documentation much like the current Guides are (1.0, 1.1, latest, etc). We should probably do this with branch names so universal updates or errata can be backported. 

We'll also want to consider a multi-language approach so we can have /fr/1.1 or something.

**Comment by thedaniel** [comment]
[Shipped!](https://atom.io/docs)
