### ISSUE TITLE
Most screenshots are out-of-date

### ISSUE THREAD

**Issue by xfq** [atom/docs#42]
The screenshot of Settings View in [this page](https://atom.io/docs/v0.189.0/getting-started-atom-basics#settings-and-preferences) is pretty old now. I think [this image](https://cloud.githubusercontent.com/assets/1476/5624241/d29ffbe6-9516-11e4-8bfe-e91623977bc7.png) from the settings-view repo can be used to replace the current one.

I haven't find a new screenshot for `ThemesPanel` (https://atom.io/docs/v0.189.0/getting-started-atom-basics#changing-the-color-theme) yet.

**Comment by mnquintana** [comment]
I think this is true of just about every screenshot in here - especially now that One Dark is the default, all of the screenshots should probably be updated to reflect that before 1.0.

**Comment by xfq** [comment]
Agreed.

**Comment by mnquintana** [comment]
Fixed by https://github.com/atom/docs/pull/90
