### ISSUE TITLE
Automatic ebook builds

### ISSUE THREAD

**Issue by schacon** [atom/docs#5]
Set up automatic ebook builds from Atlas and auto-link the builds to atom.io documentation page.

**Comment by schacon** [comment]
Thanks to their new [web hook support](http://blog.atlas.oreilly.com/2015/03/github_webhooks/), any changes to the master branch on this repo now triggers an auto-build.

**Comment by izuzak** [comment]
Yesss!! :heart_eyes_cat: 

:zap: @schacon
