### ISSUE TITLE
Keybindings in Doc are out-of-date

### ISSUE THREAD

**Issue by grandsong** [atom/docs#72]
These Doc pages need updating.

- [Atom Selections](https://atom.io/docs/latest/using-atom-atom-selections)
- [Editing and Deleting Text](https://atom.io/docs/latest/using-atom-atom-editing-and-deleting-text)

Quit a few keybindings in the doc of atom.io are incorrect.

A best example is `ctrl-shift-P` which is false explained as "Select up".

Some other examples:

- `ctrl-T`: Transpose characters. In fact, fuzzy-finder:toggle-file-finder.
- `alt-backspace`: Delete to beginning of word. In fact, no such keybinding.
- `cmd-shift-L`: Convert a multi-line selection into multiple cursors. In fact, grammar-selector:show. (Note: I'm using Windows)

**Comment by 50Wliu** [comment]
This is because the docs are currently catered towards Mac users and not Windows/Linux users.  Most of the keybindings are the same when converted from <kbd>Cmd</kbd> to <kbd>Ctrl</kbd>, but as you've seen here not everything works that way.

Please see #16 for more details.

**Comment by grandsong** [comment]
Yes, I know that and have already ruled out what I suspect are WIndow only invalid keybindings.
But I guess there are still some incorrect.
I am not sure. Hope someone can check it through.

**Comment by lee-dohm** [comment]
There is some discussion on how to better handle cross-platform keybindings in #16.

**Comment by grandsong** [comment]
I just read your topic. As I expected, some (including you) have already discussed fully about that issue. I am looking forward to the change you guys have planned.

PS: So far, and maybe even in the future, I guess the [Settings > Keybindings] is the first and last place to learn what keybindings your Atom are really using now.

Anyway, my topic here is not about cross-platform problem, although it looks so at first glance. 

I just find the doc is out-of-date. Not only about keybindings.
