### ISSUE TITLE
Package name in first package writing tutorial causes issue with not being loaded

### ISSUE THREAD

**Issue by lee-dohm** [atom/docs#85]
See: atom/settings-view#554

**Comment by alflanagan** [comment]
This has been open almost two months. At the least, what about adding a warning note to the page that "wordcount" and "word-count" can't actually be used for package names?

**Comment by alflanagan** [comment]
Further comment: not sure if this should be a documentation change, or if "wordcount" and "word-count" should be removed from file atom/resources/app/apm/deprecated-packages.json. Why were they added in the first place?
