### ISSUE TITLE
Atom's OS X command line tools are now installed on first use

### ISSUE THREAD

**Issue by UsabilityEtc** [atom/docs#96]
In the [Atom on Mac](https://atom.io/docs/latest/getting-started-installing-atom#atom-on-mac) and [Opening a File](https://atom.io/docs/latest/getting-started-atom-basics#opening-a-file) sections of the Atom Flight Manual, the text recommends installing the OS X command line utilities (`atom` and `apm`).

The latest version (1.0.2) installs `atom` and `apm` when Atom is first opened.

If this is the new default behaviour on OS X, should I update the docs to reflect this?

**Comment by kevinsawicki** [comment]
> If this is the new default behaviour on OS X, should I update the docs to reflect this?

Atom has always tried to install the command line tools on launch but sometimes can't due to permission issue. That is when it is necessary to run the menu item since it will prompt for a sudo password when needed.

**Comment by UsabilityEtc** [comment]
I think it's worth mentioning that Atom on OS X will attempt to install the command line tools but if it fails users can still install them through the menu/command palette. When it is implied in two places that Atom doesn't install the tools when in fact Atom does when it it can, subsequently finding that the tools have been installed makes the docs seem out of date. Just a thought.

**Comment by izuzak** [comment]
> I think it's worth mentioning that Atom on OS X will attempt to install the command line tools but if it fails users can still install them through the menu/command palette. 

I agree, @UsabilityEtc -- would be neat to mention that in the docs. :+1:

**Comment by UsabilityEtc** [comment]
OK, @izuzak, I'll make that change.
